Expose exchange from ipfs-lite
hsanjuan/ipfs-lite pull request #190
Opened 2021-11-28 09:04 UTC by aloknerurkar

We initialize bitswap when we create the light client. I feel it could be useful to expose this to the users.

2021-11-29 13:00 UTC, hsanjuan commented
@aloknerurkar for the record, I was happy to merge this.

2021-11-29 13:14 UTC, hsanjuan requested changes
Can you make it without the dependency updates? They are not relevant here.

2021-11-29 13:20 UTC, aloknerurkar commented
I actually closed this as I ended up updating the dependencies in my fork. There are some breaking changes. Hopefully we can update this repo soon so I dont have to maintain the fork!

2021-11-30 05:02 UTC, hsanjuan approved these changes

2021-11-30 05:03 UTC, hsanjuan commented
@aloknerurkar can you rebase on master? I have updated dependencies

2021-11-30 06:14 UTC, aloknerurkar commented
I ran `go mod tidy` and it removed `github.com/libp2p/go-libp2p-tls`. I am able to build and test so I guess its not required?

2021-11-30 14:39 UTC, merged